import boto3

from app.config import settings


def _render_html(identifiers: list[str], rows: list[dict], threshold: int) -> str:
    header_cols = [
        "Gene", "Samples", "Min Mean Cov", "Max Mean Cov",
        "Mean Mean Cov", f"Min % ≥{threshold}x", f"Mean % ≥{threshold}x",
    ]
    header_html = "".join(f"<th>{c}</th>" for c in header_cols)

    row_html = ""
    for r in sorted(rows, key=lambda x: x["gene"]):
        row_html += (
            f"<tr>"
            f"<td>{r['gene']}</td>"
            f"<td>{r['n_samples']}</td>"
            f"<td>{r['min_mean_cov']:.2f}</td>"
            f"<td>{r['max_mean_cov']:.2f}</td>"
            f"<td>{r['mean_mean_cov']:.2f}</td>"
            f"<td>{r['min_pct_nx']:.2f}%</td>"
            f"<td>{r['mean_pct_nx']:.2f}%</td>"
            f"</tr>"
        )

    query_list = ", ".join(identifiers)
    return f"""
<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: Arial, sans-serif; font-size: 14px; color: #222; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border: 1px solid #ccc; padding: 8px 12px; text-align: left; }}
  th {{ background: #f0f4f8; }}
  tr:nth-child(even) {{ background: #f9f9f9; }}
  h2 {{ color: #2c5282; }}
</style>
</head>
<body>
  <h2>Gene Coverage Report</h2>
  <p><strong>Query:</strong> {query_list}</p>
  <p><strong>Depth threshold:</strong> {threshold}x</p>
  <table>
    <thead><tr>{header_html}</tr></thead>
    <tbody>{row_html}</tbody>
  </table>
  <p style="color:#888;font-size:12px;margin-top:24px">
    Generated by gene-coverage-app
  </p>
</body>
</html>
"""


def send_report(to_email: str, identifiers: list[str], rows: list[dict]) -> None:
    html = _render_html(identifiers, rows, settings.min_depth)
    client = boto3.client("ses", region_name=settings.aws_region)
    client.send_email(
        Source=settings.ses_sender,
        Destination={"ToAddresses": [to_email]},
        Message={
            "Subject": {"Data": "Gene Coverage Report"},
            "Body": {"Html": {"Data": html}},
        },
    )
